bigint added
VankaTaganai/first-term pull request #2
Opened 2020-06-20 10:42 UTC by VankaTaganai

2020-06-20 19:55 UTC, kt-cpp requested changes

2020-06-20 19:55 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    num.push_back(a);
если a<0, то пуш в вектор беззнаковых.

2020-06-20 19:55 UTC, kt-cpp commented on bigint/big_integer.h
> +    void shrink();
нейминг пострадал. обычно добавляют нижнее подчеркивание либо impl

2020-06-20 19:55 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    std::swap(negative, tmp.negative);
нужен метод свап, а здесь использование этого метода

2020-06-20 19:55 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        number = ('0' <= str[i] && str[i] <= '9');
видимо здесь ожидалось &&

2020-06-20 19:55 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (str[0] == '-') {
а если строка пустая?

2020-06-20 19:55 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (negative) {
тернарный оператор

2020-06-20 19:55 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        num[i] = uint32_t(carry);
а если переполнение? то же самое в умножении.

2020-06-20 19:55 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            num[index] = (uint32_t)carry;
переполнение

2020-06-20 19:55 UTC, kt-cpp commented
Кстати в ПР попал вектор из первой дз...

2020-06-20 20:00 UTC, VankaTaganai commented
> попал

Я просто использую свой вектор

2020-06-20 20:01 UTC, VankaTaganai commented
> Кстати в ПР попал вектор из первой дз...

Я просто использую свой вектор в реализации

2020-06-21 15:03 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    num.push_back(a);
fixed

2020-06-21 15:03 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    std::swap(negative, tmp.negative);
fixed

2020-06-21 15:03 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +        number = ('0' <= str[i] && str[i] <= '9');
fixed

2020-06-21 15:03 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    if (str[0] == '-') {
fixed

2020-06-21 15:03 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    if (negative) {
fixed

2020-06-21 15:03 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +        num[i] = uint32_t(carry);
Я просто беру младшие 32 бита, кажется это легально.

2020-06-21 15:04 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +            num[index] = (uint32_t)carry;
Я просто беру младшие 32 бита, кажется это легально.

2020-06-21 15:19 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    if (str[0] == '-') {
тут не может быть пустой строки, выше проверка

2020-06-21 15:22 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    num.push_back(a);
вроде нет проблем, я храню числа в дополнении до двух

2020-06-21 16:18 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        num[i] = uint32_t(carry);
1) Сишный каст
2) Ты проверил стандарт на то, что каст оставляет младшие 32 бита ровно в случае переполнения?

2020-06-21 16:18 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            num[index] = (uint32_t)carry;
Читай коммент выше

2020-06-21 16:43 UTC, kt-cpp requested changes

2020-06-21 16:43 UTC, kt-cpp commented on bigint/vector.h
> +    static T* allocate(size_t size);
Зачем эти функции в публичном доступе?

2020-06-21 16:43 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    num.push_back((uint32_t) a);
Кажется этот и другие подобные касты знакового к беззнаковому inplementation scpecific

2020-06-21 16:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    num.push_back(a);
Отписал о подобных местах в новом ревью

2020-06-21 16:45 UTC, kt-cpp commented
Ну и нет никаких причин использовать тут свой вектор. Этим удваивается работа как проверяющему так и студенту

2020-06-21 16:46 UTC, VankaTaganai commented on bigint/vector.h
> +    static T* allocate(size_t size);
Они приватные

2020-06-21 16:47 UTC, VankaTaganai commented
> Ну и нет никаких причин использовать тут свой вектор. Этим удваивается работа как проверяющему так и студенту

Я не вижу проблемы, так как мне уже зачли вектор

2020-06-21 17:21 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    num.push_back(a);
fixed

2020-06-21 17:22 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +        num[i] = uint32_t(carry);
Заменил все касты на плюсовые и решил проблему с переполнением

2020-06-21 17:22 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +            num[index] = (uint32_t)carry;
fixed

2020-06-21 17:22 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    num.push_back((uint32_t) a);
fixed

2020-06-21 22:38 UTC, kt-cpp requested changes

2020-06-21 22:38 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return std::min(static_cast<uint32_t>(x / y), UINT32_MAX);
Каст должен быть снаружи раз результат деления может быть больше чем `UINT32_MAX`

2020-06-21 22:38 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        uint64_t diff = (static_cast<uint64_t>(r.get_byte(start + i)) - dq.get_byte(i) - borrow);
Изначально было знаковое, а сейчас может произойти переполнение беззнакового. Но даже со знаковым ты на 2 строки ниже писал отрицательное в `uit32_t`

2020-06-21 22:38 UTC, kt-cpp commented on bigint/big_integer.cpp
> +}
Гитхаб прям намекает, что забыл пустую строку в конце

2020-06-21 22:38 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        x.num[i] = static_cast<uint32_t>(tmp / k);
А что по поводу переполнения?

2020-06-21 22:38 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t f = (static_cast<uint64_t>(UINT32_MAX) + 1) / (static_cast<uint64_t>(divr.num.back()) + 1);
Тут забыли каст результата в `uint32_t`. И снова вопрос что тут с переполнениями `uint32_t` в результате

2020-06-22 07:47 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    return std::min(static_cast<uint32_t>(x / y), UINT32_MAX);
fixed

2020-06-22 07:48 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +        uint64_t diff = (static_cast<uint64_t>(r.get_byte(start + i)) - dq.get_byte(i) - borrow);
Должно быть беззнаковое, переполнение пофиксил

2020-06-22 07:48 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +}
fixed

2020-06-22 07:49 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +        x.num[i] = static_cast<uint32_t>(tmp / k);
fixed

2020-06-22 07:49 UTC, VankaTaganai commented on bigint/big_integer.cpp
> +    uint32_t f = (static_cast<uint64_t>(UINT32_MAX) + 1) / (static_cast<uint64_t>(divr.num.back()) + 1);
fixed

2020-06-22 10:38 UTC, kt-cpp approved these changes

2020-06-22 10:38 UTC, merged