asm added
VankaTaganai/first-term pull request #4
Opened 2020-06-24 19:03 UTC by VankaTaganai

2020-06-26 22:10 UTC, kt-cpp commented on asm/mul.asm
> +                push            rdi
контракт, очевидным образом не выполняется

2020-06-26 22:10 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rbx, [rdi - 2 * 128 * 8]
Почему в двух строчках по разному делаются похожие операции?

2020-06-26 22:11 UTC, kt-cpp commented on asm/mul.asm
> +                call            set_zero
Почему нельзя подвинуть ```rcx``` и не мучаться

2020-06-26 22:12 UTC, kt-cpp commented on asm/mul.asm
> +                xor             rdx, rdx
Зачем здесь эта строчка? :)

2020-06-26 22:12 UTC, kt-cpp commented on asm/mul.asm
> +                mov             r11, 0
Тут можно ```xor r11, r11```, но это мелочь

2020-06-26 22:13 UTC, kt-cpp requested changes
Главное: сделай так чтобы контракт выполнялся (или поменяй контракт)

2020-06-27 05:49 UTC, VankaTaganai commented on asm/mul.asm
> +                mov             r11, 0
Если так сделать, то кери флаг станет нулем, поэтому я так и сделал.

2020-06-27 05:50 UTC, VankaTaganai commented on asm/mul.asm
> +                xor             rdx, rdx
fixed

2020-06-27 05:50 UTC, VankaTaganai commented on asm/mul.asm
> +                lea             rbx, [rdi - 2 * 128 * 8]
fixed

2020-06-27 05:59 UTC, VankaTaganai commented on asm/mul.asm
> +                call            set_zero
fixed

2020-06-27 05:59 UTC, VankaTaganai commented on asm/mul.asm
> +                push            rdi
fixed

2020-06-27 13:05 UTC, kt-cpp commented on asm/mul.asm
> +                mov             r11, 0
Хм, я всегда считал, что ```xor``` не аффектит ```CF```. Ок.

2020-06-27 13:09 UTC, merged